### ISSUE TITLE
Ability to specify a configuration file to load credentials from

### ISSUE THREAD

**Issue by Johnlon** [bmuschko/gradle-nexus-plugin#55]
I understand that the recommendation is to put nexusUsername/password into gradle,properties.

However for various reasons this is difficult for me - basically I can't use the gradle.properties for this purpose and in anycase I wish to segregate the credentials from any other config I hold.

In my build environment I cannot influence the contents of $HOME so cannot rely on $HOME so can't put gradle.properties there.

Additionally I'm using 'Force GRADLE_USER_HOME to use workspace' in Jenkins and it is undesirable for me to place gradle.properties in the workspace.

So for me the gradle.properties approach isn't a good fit.

I would like a convenient method to tell the nexus plugin which file to look in for the props.

The following is a usage suggestion just for illustration and discussion ... 

```
nexus {
     credentialsProperties file("/someLocationOfMyChoosing/nexus.credentials")
}
```

Where the file would contain ...

```
nexusUsername="hello"
nexusPassword="there"
```

The credentialsProperties location should be inspected ONLY if the credentials are required - ie only if I'm executing an upload task that needs the credentials..

I can of course hand crank something that optionally loads the properties in a manner that keeps the nexus plugin happy ...

```
// at top of gradle.build
ext.credentialsProperties=file("/someLocationOfMyChoosing/nexus.credentials")
if (ext.credentialsProperties.exists()) {
    apply from: ext.credentialsProperties
}
```

With the file containing something like ...

```
ext {
        nexusUsername="hello"
        nexusPassword="there"
}

```

However I would much rather just have something like the suggestion I made above as it is a one liner.

Please give your opinion on this suggestion and other options for plumbing the credentials properties into place.

PS Happy to do the work.

**Comment by bmuschko** [comment]
> I understand that the recommendation is to put nexusUsername/password into gradle,properties.

I should restate that in the README file. It's really an option. I am going to change the wording when I have a minute.

> However I would much rather just have something like the suggestion I made above as it is a one liner.

I mentioned that in another issue as well. Reading credentials from any source should really be a totally separate plugin - simply because people have different use cases and it's not really the main concern of this plugin. That's also the case for the handling we have in place for reading credentials from the console. This was an external contribution and unfortunately I accepted it. I am not going to add any more additions on the plugin for handling other ways to read credentials. In fact I'd rather go the other way and completely extract it.

> Please give your opinion on this suggestion and other options for plumbing the credentials properties into place.

Anything can be implemented. It depends on how you want it to work. You could read the credentials through HTTP from an internal server or from a JSON file for example. You can also wrap this plugin by another plugin and implement the handling you need.

**Comment by bmuschko** [comment]
The Nexus plugin won't provide additional options to configure credentials. I am going to close this issue.
